### ISSUE TITLE
How to get product images with v3?

### ISSUE THREAD

**Issue by shanejdonnelly** [Epic-Design-Labs/gatsby-source-bigcommerce#8]
I'm new to GraphQL, so sorry if this question is off. It seems that BigCommerce images are found with this endpoint, which has a path parameter -> `/catalog/products/{product_id}/images`

I see how I would set up an endpoint in the config to get images for a single product:
```
 `BigCommerceProductImages: `/catalog/products/${product_id}/images`
```

But I can't figure out how to have a page query get images dynamically. Something like this:
```
export const productPageQuery = graphql`
  query ProductPage($product_id: String!) {
    allBigCommerceProductImages (product_id: $product_id) {
      nodes {
        url_thumbnail
        url_standard
      }
    }
  }
`;
```

The same question seems like it might apply to product variants as well. 

Thanks for any help you can provide. And thanks again for your work on this repo, it works great for getting products, brands and categories (and probably other stuff I haven't tried yet).

**Comment by guy-epicdesignlabs** [comment]
@shanejdonnelly Hey there. I will investigate this issue and get back to you the soonest. I will provide updates on the repo soon.

**Comment by guy-epicdesignlabs** [comment]
@shanejdonnelly I will consider this as a new feature that I'll be working on soon. As of right now, this source plugin will only support endpoints that doesn't require dynamic data for fetching additional data - so, endpoints like `
/catalog/products/{product_id}/images` won't work, at least for now. But I'll change that as it seems that BigCommerce API has a lot of endpoints that require dynamic data which are quite essential.

**Comment by shanejdonnelly** [comment]
Thanks @guy-epicdesignlabs ! Let me know if I can be of help. Once you have an one method wired up, I'm sure I could help fill out others.

**Comment by jmoggach** [comment]
Hey @shanejdonnelly ,

Not sure if this helps but there's a nice example of how this can be done in API v3 in the [Gatsby + BigCommerce + Netlify CMS Starter](https://github.com/bigcommerce/gatsby-bigcommerce-netlify-cms-starter/blob/master/gatsby-config.js)

You can append an `?include` parameter to the API path to include Product content from other models:

```
BigCommerceProducts: "/catalog/products?include=images",
```

This will include images within the product entry in Gatsby's GraphQL endpoint. You can then run a query like the following to grab the image details

```
query ProductQuery {
  allBigCommerceProducts {
    nodes {
      name
      sku
      images {
        url_standard
        url_thumbnail
      }
    }
  }
}
```

The `?include` parameter takes a bunch of other handy values like 'variants', 'videos' and 'custom_fields' too.

**Comment by guy-epicdesignlabs** [comment]
@jmoggach Yeah, thanks for pointing that one out. I forgot to mention that. Sorry about that.
